# Generated by Django 4.1.3 on 2023-01-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwords',
            name='site',
            field=models.TextField(default=' '),
        ),
    ]
